# Abstract {#abstract}

The immune system remodelling occurring with ageing, known as immunosenescence, contributes to increased susceptibility of the elderly to infectious diseases, cancer, autoimmunity, and decreased responses to vaccines. This remodelling is a poorly understood complex process that involves multiple factors. For instance, we still don’t known about the molecular mechanisms involved in immunosenescence and how they can be caused by primary problems, such as early perturbations in biological processes or secondary problems, such as those caused by a failed response to achieve homeostasis, isturbed b y primary problems.

Here we applied a Systems Biology framework to study the remodelling of the immune system by analysis of blood transcriptional profiles. We aim to understand how changes in the expression of immune components during life are related to immunosenescence. To this end, we developed novel methods tailored to identify and describe pathways and genes serving as biomarker of ageing. We applied these methods to a massive dataset from 1807 blood samples from healthy subjects gathered from public gene expression repositories.

We found 56 transcripts correlated with age, which suggests that signal transduction pathways and cytokines in regulating T lymphocytes, especially regulatory, are important to cell proliferation and senescence. Coexpression modules related to innate and adaptive immune system signalling were identified. Changes in global expression patterns in these modules reveal imbalances in signal transduction mechanisms regulating the interaction between the innate and adaptive immune system, probably due to the deregulation of TLR activation pathways and the production of cytokines induced by NF-kB. We identified changes in these expression profiles around the age of 30 years and around the age of 55-60 years. These results suggest that transcriptional changes, that are characteristic of immunosenescence, occur at a young age and intensify with ageing.

The methodologies developed in this study allowed us to find transcriptional disorders matching morphological changes described in the literature and enabled us to identify new transcripts and biological processes not yet associated to immunosenescence. Such methodologies can be optimized and adapted not only to higher-quality transcriptomics assessment techniques, such as RNA-Seq, but also to other levels of biological information, such as metabolomics, proteomics, etc. We expect that our findings may assist in the comprehension of mechanisms involved in immunosenescence, and to aid in the creation of interventions capable of beneficial regulation of remodelling of the immune system during life, allowing the extension of a life with quality.